In [120]:
import pandas as pd

df = pd.read_csv("static/output_file.csv")
df

,id,Tipo_Cotizante,Subtipo_Cotizante,Subtipo_UGPP,Tipo_Identificacion,Identificacion,Primer_Nombre,Segundo_Nombre,Primer_Apellido,Segundo_Apellido,...,ICBTarifa,Valor_PILA,Valor_Otros,Valor_Total,Incapacidades,Tipo_Periodo,Modo_Recaudo,Numero_Nit,Razon_Social,Observaciones
0,1,1,7,0,CC,38596006,MARIA,TERSELINA,AGUILAR,ZUÑIGA,...,NaN,58700,0,105700,0,Vigente,Comprobante,901643091,C&C ACCION LEGAL SAS,NaN
1,2,1,7,0,CC,94537793,JONNY,ALEXANDER,ALARCON,GARCIA,...,NaN,105100,0,152100,0,Vigente,Comprobante,901643091,C&C ACCION LEGAL SAS,NaN
2,3,1,3,3.4,CC,31952188,ROSALBINA,NaN,ALMENDRA,SANCHEZ,...,NaN,98900,0,145900,0,Vigente,Comprobante,901643091,C&C ACCION LEGAL SAS,NaN
3,4,1,7,0,CC,1130637513,HERMINIA,ANDREA,ALVARADO,LONDOÑO,...,NaN,39500,0,86500,0,Vigente,Comprobante,901643091,C&C ACCION LEGAL SAS,NaN
4,5,1,3,3,CC,12127358,HECTOR,FERNANDO,ALVAREZ,CASTRO,...,NaN,96900,0,143900,0,Vigente,Comprobante,901643091,C&C ACCION LEGAL SAS,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68,78,1,0,**,CC,1107083261,DANIELA,NaN,VELEZ,TAPIAS,...,NaN,284500,0,331500,0,Vigente,Comprobante,901643091,C&C ACCION LEGAL SAS,NaN
69,79,1,3,3.4,CC,36531713,BETTY,NaN,VILLA,ROJAS,...,NaN,52500,0,99500,0,Vigente,Comprobante,901643091,C&C ACCION LEGAL SAS,NaN
70,80,1,0,**,CC,66991031,DALIA,FANNY,VIVERO,ASPRILLA,...,NaN,284500,0,326500,0,Vigente,Comprobante,901643091,C&C ACCION LEGAL SAS,NaN
71,81,1,0,**,CC,1077631446,BETTY,AMELIA,VIVEROS,ASPRILLA,...,NaN,284500,0,326500,0,Vigente,Comprobante,901643091,C&C ACCION LEGAL SAS,NaN
72,82,1,7,0,CC,94369810,ANDRES,NaN,ZOTA,CASTRO,...,NaN,52900,0,99900,0,Vigente,Comprobante,901643091,C&C ACCION LEGAL SAS,NaN

In [121]:
deleted_cols=["id","Subtipo_UGPP", "Subtipo_Cotizante", "Tipo_Cotizante", "ICBTarifa", "Valor_Otros", "SENATarifa", "ICBF", "SENA", "Identificacion_Cotizante_UPC", "Excento_de_1607", "Centro_Trabajo", "Numero_Folio", "Nit_Empresa_Servicio", "Razon_Social_Empresa_Servicio" ]
df=df.drop(columns=deleted_cols)
df.head()

,Tipo_Identificacion,Identificacion,Primer_Nombre,Segundo_Nombre,Primer_Apellido,Segundo_Apellido,Tipo_Sexo,Salario_o_IBC,Cotizante_Extranjero,Fecha_Nacimiento,...,Ciudad_CCF,CCFTarifa,Valor_PILA,Valor_Total,Incapacidades,Tipo_Periodo,Modo_Recaudo,Numero_Nit,Razon_Social,Observaciones
0,CC,38596006,MARIA,TERSELINA,AGUILAR,ZUÑIGA,F,1160000,Ninguno,1981-02-14,...,PUERTO CARREÑO (VICHADA),0.00,58700,105700,0,Vigente,Comprobante,901643091,C&C ACCION LEGAL SAS,NaN
1,CC,94537793,JONNY,ALEXANDER,ALARCON,GARCIA,M,1160000,Ninguno,1984-09-26,...,CALI (VALLE DEL CAUCA),0.04,105100,152100,0,Vigente,Comprobante,901643091,C&C ACCION LEGAL SAS,NaN
2,CC,31952188,ROSALBINA,NaN,ALMENDRA,SANCHEZ,F,1160000,Ninguno,1956-02-27,...,CALI (VALLE DEL CAUCA),0.04,98900,145900,0,Vigente,Comprobante,901643091,C&C ACCION LEGAL SAS,NaN
3,CC,1130637513,HERMINIA,ANDREA,ALVARADO,LONDOÑO,F,1160000,Ninguno,1987-11-30,...,PUERTO CARREÑO (VICHADA),0.00,39500,86500,0,Vigente,Comprobante,901643091,C&C ACCION LEGAL SAS,NaN
4,CC,12127358,HECTOR,FERNANDO,ALVAREZ,CASTRO,M,1160000,Ninguno,1962-08-08,...,PUERTO CARREÑO (VICHADA),0.00,96900,143900,0,Vigente,Comprobante,901643091,C&C ACCION LEGAL SAS,NaN

In [122]:
df.columns

Index(['Tipo_Identificacion', 'Identificacion', 'Primer_Nombre',
       'Segundo_Nombre', 'Primer_Apellido', 'Segundo_Apellido', 'Tipo_Sexo',
       'Salario_o_IBC', 'Cotizante_Extranjero', 'Fecha_Nacimiento', 'Edad',
       'Fecha_Expedicion', 'Numero_Telefono', 'Numero_Celular', 'Direccion',
       'Ciudad_Departamento', 'Email', 'Vlr_Administracion', 'Vlr_UPC',
       'Mensajeria', 'Vlr_Mensajeria', 'Estado', 'Identificacion_Asesor',
       'Nombre_Asesor', 'Valor_Comision', 'Fecha_Afiliacion', 'AFP',
       'AFPTarifa', 'EPS', 'EPSTarifa', 'ARL', 'ARLTarifa', 'ARL_Nivel',
       'CodCIIU', 'Planilla_N', 'CCF', 'Ciudad_CCF', 'CCFTarifa', 'Valor_PILA',
       'Valor_Total', 'Incapacidades', 'Tipo_Periodo', 'Modo_Recaudo',
       'Numero_Nit', 'Razon_Social', 'Observaciones'],
      dtype='object')

In [123]:
df.to_csv("static/new_output_file.csv", index=False)

In [124]:
df["Ciudad_Departamento"]==df["Ciudad_CCF"]

0     False
1      True
2      True
3     False
4     False
      ...
68     True
69    False
70     True
71     True
72    False
Length: 73, dtype: bool

In [125]:
df_updated=pd.read_csv("static/new_output_file.csv", encoding="latin1")
df_updated

,Tipo_Identificacion,Identificacion,Primer_Nombre,Segundo_Nombre,Primer_Apellido,Segundo_Apellido,Tipo_Sexo,Salario_o_IBC,Cotizante_Extranjero,Fecha_Nacimiento,...,Ciudad_CCF,CCFTarifa,Valor_PILA,Valor_Total,Incapacidades,Tipo_Periodo,Modo_Recaudo,Numero_Nit,Razon_Social,Observaciones
0,CC,38596006,MARIA,TERSELINA,AGUILAR,ZUÃIGA,F,1160000,Ninguno,1981-02-14,...,PUERTO CARREÃO (VICHADA),0.00,58700,105700,0,Vigente,Comprobante,901643091,C&C ACCION LEGAL SAS,NaN
1,CC,94537793,JONNY,ALEXANDER,ALARCON,GARCIA,M,1160000,Ninguno,1984-09-26,...,CALI (VALLE DEL CAUCA),0.04,105100,152100,0,Vigente,Comprobante,901643091,C&C ACCION LEGAL SAS,NaN
2,CC,31952188,ROSALBINA,NaN,ALMENDRA,SANCHEZ,F,1160000,Ninguno,1956-02-27,...,CALI (VALLE DEL CAUCA),0.04,98900,145900,0,Vigente,Comprobante,901643091,C&C ACCION LEGAL SAS,NaN
3,CC,1130637513,HERMINIA,ANDREA,ALVARADO,LONDOÃO,F,1160000,Ninguno,1987-11-30,...,PUERTO CARREÃO (VICHADA),0.00,39500,86500,0,Vigente,Comprobante,901643091,C&C ACCION LEGAL SAS,NaN
4,CC,12127358,HECTOR,FERNANDO,ALVAREZ,CASTRO,M,1160000,Ninguno,1962-08-08,...,PUERTO CARREÃO (VICHADA),0.00,96900,143900,0,Vigente,Comprobante,901643091,C&C ACCION LEGAL SAS,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68,CC,1107083261,DANIELA,NaN,VELEZ,TAPIAS,F,1160000,Ninguno,1994-06-23,...,CALI (VALLE DEL CAUCA),0.04,284500,331500,0,Vigente,Comprobante,901643091,C&C ACCION LEGAL SAS,NaN
69,CC,36531713,BETTY,NaN,VILLA,ROJAS,F,1160000,Ninguno,1952-11-21,...,PUERTO CARREÃO (VICHADA),0.00,52500,99500,0,Vigente,Comprobante,901643091,C&C ACCION LEGAL SAS,NaN
70,CC,66991031,DALIA,FANNY,VIVERO,ASPRILLA,F,1160000,Ninguno,1975-11-11,...,CALI (VALLE DEL CAUCA),0.04,284500,326500,0,Vigente,Comprobante,901643091,C&C ACCION LEGAL SAS,NaN
71,CC,1077631446,BETTY,AMELIA,VIVEROS,ASPRILLA,F,1160000,Ninguno,1984-08-07,...,CALI (VALLE DEL CAUCA),0.04,284500,326500,0,Vigente,Comprobante,901643091,C&C ACCION LEGAL SAS,NaN
72,CC,94369810,ANDRES,NaN,ZOTA,CASTRO,M,1160000,Ninguno,1972-04-13,...,PUERTO CARREÃO (VICHADA),0.00,52900,99900,0,Vigente,Comprobante,901643091,C&C ACCION LEGAL SAS,NaN

In [126]:
df_updated[["Numero_Telefono", "Numero_Celular"]] = df_updated[["Numero_Telefono", "Numero_Celular"]].astype(str)
df_updated[["Numero_Telefono", "Numero_Celular"]] = df_updated[["Numero_Telefono", "Numero_Celular"]].map(lambda x: '' if x == '0' else x)
# df_updated.drop(columns="id")
df_updated

,Tipo_Identificacion,Identificacion,Primer_Nombre,Segundo_Nombre,Primer_Apellido,Segundo_Apellido,Tipo_Sexo,Salario_o_IBC,Cotizante_Extranjero,Fecha_Nacimiento,...,Ciudad_CCF,CCFTarifa,Valor_PILA,Valor_Total,Incapacidades,Tipo_Periodo,Modo_Recaudo,Numero_Nit,Razon_Social,Observaciones
0,CC,38596006,MARIA,TERSELINA,AGUILAR,ZUÃIGA,F,1160000,Ninguno,1981-02-14,...,PUERTO CARREÃO (VICHADA),0.00,58700,105700,0,Vigente,Comprobante,901643091,C&C ACCION LEGAL SAS,NaN
1,CC,94537793,JONNY,ALEXANDER,ALARCON,GARCIA,M,1160000,Ninguno,1984-09-26,...,CALI (VALLE DEL CAUCA),0.04,105100,152100,0,Vigente,Comprobante,901643091,C&C ACCION LEGAL SAS,NaN
2,CC,31952188,ROSALBINA,NaN,ALMENDRA,SANCHEZ,F,1160000,Ninguno,1956-02-27,...,CALI (VALLE DEL CAUCA),0.04,98900,145900,0,Vigente,Comprobante,901643091,C&C ACCION LEGAL SAS,NaN
3,CC,1130637513,HERMINIA,ANDREA,ALVARADO,LONDOÃO,F,1160000,Ninguno,1987-11-30,...,PUERTO CARREÃO (VICHADA),0.00,39500,86500,0,Vigente,Comprobante,901643091,C&C ACCION LEGAL SAS,NaN
4,CC,12127358,HECTOR,FERNANDO,ALVAREZ,CASTRO,M,1160000,Ninguno,1962-08-08,...,PUERTO CARREÃO (VICHADA),0.00,96900,143900,0,Vigente,Comprobante,901643091,C&C ACCION LEGAL SAS,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68,CC,1107083261,DANIELA,NaN,VELEZ,TAPIAS,F,1160000,Ninguno,1994-06-23,...,CALI (VALLE DEL CAUCA),0.04,284500,331500,0,Vigente,Comprobante,901643091,C&C ACCION LEGAL SAS,NaN
69,CC,36531713,BETTY,NaN,VILLA,ROJAS,F,1160000,Ninguno,1952-11-21,...,PUERTO CARREÃO (VICHADA),0.00,52500,99500,0,Vigente,Comprobante,901643091,C&C ACCION LEGAL SAS,NaN
70,CC,66991031,DALIA,FANNY,VIVERO,ASPRILLA,F,1160000,Ninguno,1975-11-11,...,CALI (VALLE DEL CAUCA),0.04,284500,326500,0,Vigente,Comprobante,901643091,C&C ACCION LEGAL SAS,NaN
71,CC,1077631446,BETTY,AMELIA,VIVEROS,ASPRILLA,F,1160000,Ninguno,1984-08-07,...,CALI (VALLE DEL CAUCA),0.04,284500,326500,0,Vigente,Comprobante,901643091,C&C ACCION LEGAL SAS,NaN
72,CC,94369810,ANDRES,NaN,ZOTA,CASTRO,M,1160000,Ninguno,1972-04-13,...,PUERTO CARREÃO (VICHADA),0.00,52900,99900,0,Vigente,Comprobante,901643091,C&C ACCION LEGAL SAS,NaN

In [127]:
tipos_de_datos = df_updated.dtypes
pd.option_context('display.max_rows', None, 'display.max_columns', None, 'display.width', None)
print(df_updated.dtypes)

Tipo_Identificacion       object
Identificacion             int64
Primer_Nombre             object
Segundo_Nombre            object
Primer_Apellido           object
Segundo_Apellido          object
Tipo_Sexo                 object
Salario_o_IBC              int64
Cotizante_Extranjero      object
Fecha_Nacimiento          object
Edad                       int64
Fecha_Expedicion          object
Numero_Telefono           object
Numero_Celular            object
Direccion                 object
Ciudad_Departamento       object
Email                     object
Vlr_Administracion         int64
Vlr_UPC                    int64
Mensajeria                object
Vlr_Mensajeria             int64
Estado                    object
Identificacion_Asesor    float64
Nombre_Asesor            float64
Valor_Comision             int64
Fecha_Afiliacion          object
AFP                       object
AFPTarifa                float64
EPS                       object
EPSTarifa                float64
ARL                       object
ARLTarifa                float64
ARL_Nivel                  int64
CodCIIU                    int64
Planilla_N                object
CCF                       object
Ciudad_CCF                object
CCFTarifa                float64
Valor_PILA                 int64
Valor_Total                int64
Incapacidades              int64
Tipo_Periodo              object
Modo_Recaudo              object
Numero_Nit                 int64
Razon_Social              object
Observaciones            float64
dtype: object

In [128]:
# df_updated.drop(columns=["Modo_Recaudo", "Tipo_Periodo", "Razon_Social" ])
df_updated[['Observaciones', 'CodCIIU']] = df_updated[['Observaciones', 'CodCIIU']].astype(str)
df_updated.columns=df.columns.str.lower()
df_updated.to_csv("static/new_output_file.csv", index=False)
df_updated.columns

Index(['tipo_identificacion', 'identificacion', 'primer_nombre',
       'segundo_nombre', 'primer_apellido', 'segundo_apellido', 'tipo_sexo',
       'salario_o_ibc', 'cotizante_extranjero', 'fecha_nacimiento', 'edad',
       'fecha_expedicion', 'numero_telefono', 'numero_celular', 'direccion',
       'ciudad_departamento', 'email', 'vlr_administracion', 'vlr_upc',
       'mensajeria', 'vlr_mensajeria', 'estado', 'identificacion_asesor',
       'nombre_asesor', 'valor_comision', 'fecha_afiliacion', 'afp',
       'afptarifa', 'eps', 'epstarifa', 'arl', 'arltarifa', 'arl_nivel',
       'codciiu', 'planilla_n', 'ccf', 'ciudad_ccf', 'ccftarifa', 'valor_pila',
       'valor_total', 'incapacidades', 'tipo_periodo', 'modo_recaudo',
       'numero_nit', 'razon_social', 'observaciones'],
      dtype='object')

In [135]:
# Columnas para la tabla empleados
empleados_columns = ['tipo_identificacion', 'identificacion', 'primer_nombre', 'segundo_nombre', 'primer_apellido', 
                     'segundo_apellido', 'tipo_sexo', 'cotizante_extranjero', 'fecha_nacimiento', 'edad', 'fecha_expedicion',
                     'incapacidades']

# Columnas para la tabla detalles_contacto
detalles_contacto_columns = ['numero_telefono', 'numero_celular', 'direccion', 
                             'ciudad_departamento', 'email', 'observaciones']

# Columnas para la tabla detalles_salario
detalles_salario_columns = ['salario_o_ibc', 'mensajeria', 'vlr_mensajeria', 'vlr_administracion',
                            'vlr_upc', 'estado', 'valor_pila', 'valor_total']

# Columnas para la tabla detalles_afiliacion
detalles_afiliacion_columns = ['fecha_afiliacion', 'identificacion_asesor', 'nombre_asesor', 
                               'valor_comision', 'afp', 'afptarifa', 'eps', 'epstarifa', 'arl', 'arltarifa', 'arl_nivel', 
                               'codciiu', 'planilla_n', 'ccf', 'ciudad_ccf', 'ccftarifa',]

In [158]:
# Crear sub-DataFrames
df_empleados = df_updated[empleados_columns]
df_detalles_contacto = df_updated[detalles_contacto_columns]
df_detalles_salario = df_updated[detalles_salario_columns]
df_detalles_afiliacion = df_updated[detalles_afiliacion_columns]
df_detalles_afiliacion

,fecha_afiliacion,identificacion_asesor,nombre_asesor,valor_comision,afp,afptarifa,eps,epstarifa,arl,arltarifa,arl_nivel,codciiu,planilla_n,ccf,ciudad_ccf,ccftarifa
0,2023-05-01,NaN,NaN,0,COLPENSIONES,0.16,EPS SANITAS,0.04,ARL SURA,0.00522,1,1461001,NO,COMCAJA - CAJA DE COMPENSACION FAMILIAR CAMPESINA,PUERTO CARREÃO (VICHADA),0.00
1,2023-07-01,NaN,NaN,0,PROTECCION,0.16,EPS SURA,0.04,ARL SURA,0.00522,1,1461001,NO,COMFANDI - CAJA DE COMPENSACION FAMILIAR DEL V...,CALI (VALLE DEL CAUCA),0.04
2,2023-07-01,NaN,NaN,0,NaN,NaN,NUEVA EPS,0.04,ARL SURA,0.00522,1,1461001,NO,COMFANDI - CAJA DE COMPENSACION FAMILIAR DEL V...,CALI (VALLE DEL CAUCA),0.04
3,2023-10-12,NaN,NaN,0,PORVENIR,0.16,EPS SANITAS,0.04,ARL SURA,0.00522,1,1461001,NO,COMCAJA - CAJA DE COMPENSACION FAMILIAR CAMPESINA,PUERTO CARREÃO (VICHADA),0.00
4,2023-07-01,NaN,NaN,0,NaN,NaN,NUEVA EPS,0.04,ARL SURA,0.04350,4,4461001,NO,COMCAJA - CAJA DE COMPENSACION FAMILIAR CAMPESINA,PUERTO CARREÃO (VICHADA),0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68,2023-07-01,NaN,NaN,0,COLPENSIONES,0.16,NUEVA EPS,0.04,ARL SURA,0.00522,1,1461001,NO,COMFANDI - CAJA DE COMPENSACION FAMILIAR DEL V...,CALI (VALLE DEL CAUCA),0.04
69,2023-07-01,NaN,NaN,0,NaN,NaN,SALUD TOTAL EPS,0.04,ARL SURA,0.00522,1,1461001,NO,COMCAJA - CAJA DE COMPENSACION FAMILIAR CAMPESINA,PUERTO CARREÃO (VICHADA),0.00
70,2023-07-01,NaN,NaN,0,COLPENSIONES,0.16,EPS SANITAS,0.04,ARL SURA,0.00522,1,1461001,NO,COMFANDI - CAJA DE COMPENSACION FAMILIAR DEL V...,CALI (VALLE DEL CAUCA),0.04
71,2023-08-09,NaN,NaN,0,COLFONDOS,0.16,EPS SURA,0.04,ARL SURA,0.00522,1,1461001,NO,COMFANDI - CAJA DE COMPENSACION FAMILIAR DEL V...,CALI (VALLE DEL CAUCA),0.04
72,2023-07-01,NaN,NaN,0,PROTECCION,0.16,SALUD TOTAL EPS,0.04,ARL SURA,0.00000,0,1461001,NO,COMCAJA - CAJA DE COMPENSACION FAMILIAR CAMPESINA,PUERTO CARREÃO (VICHADA),0.00

In [141]:
# Convert "Ninguno" to False, and everything else to True
df_empleados["cotizante_extranjero"] = df_empleados["cotizante_extranjero"].replace({"Ninguno": False}).astype(bool)

df_empleados.to_csv("static/employees.csv", index=False)
df_empleados.head()

/tmp/ipykernel_97833/659688074.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_empleados["cotizante_extranjero"] = df_empleados["cotizante_extranjero"].replace({"Ninguno": False}).astype(bool)

,tipo_identificacion,identificacion,primer_nombre,segundo_nombre,primer_apellido,segundo_apellido,tipo_sexo,cotizante_extranjero,fecha_nacimiento,edad,fecha_expedicion,incapacidades
0,CC,38596006,MARIA,TERSELINA,AGUILAR,ZUÃIGA,F,False,1981-02-14,42,2000-11-21,0
1,CC,94537793,JONNY,ALEXANDER,ALARCON,GARCIA,M,False,1984-09-26,39,2002-11-13,0
2,CC,31952188,ROSALBINA,NaN,ALMENDRA,SANCHEZ,F,False,1956-02-27,67,1984-12-28,0
3,CC,1130637513,HERMINIA,ANDREA,ALVARADO,LONDOÃO,F,False,1987-11-30,35,2006-04-12,0
4,CC,12127358,HECTOR,FERNANDO,ALVAREZ,CASTRO,M,False,1962-08-08,61,1983-07-27,0

In [142]:
# Obtener la longitud del DataFrame df_detalles_contacto
num_filas = len(df_detalles_contacto)

# Generar una secuencia de números para empleado_id
# Comenzando desde 1 hasta el número de filas en el DataFrame
empleado_ids = range(1, num_filas + 1)

# Insertar la columna 'empleado_id' al principio del DataFrame
df_detalles_contacto.insert(0, 'empleado_id', empleado_ids)

# Guardar el DataFrame en un archivo CSV
df_detalles_contacto.to_csv("static/contact_details.csv", index=False)
# df_detalles_contacto.to_csv("static/contact_details.csv", index=False)
df_detalles_contacto.head()

,empleado_id,numero_telefono,numero_celular,direccion,ciudad_departamento,email,observaciones
0,1,,3206159094,CARRERA 83E #53A-33,CALI (VALLE DEL CAUCA),iecidecalina@gmail.com,nan
1,2,,3226209131,CRA 25 # 14C-52,CALI (VALLE DEL CAUCA),jonny.alarcong@gmail.com,nan
2,3,,316511631,Carrera 38 # 12 A -119,CALI (VALLE DEL CAUCA),carlinauy@hotmail.com,nan
3,4,,3153330410,CALLE 48 #111-28 BOCHALEMA,CALI (VALLE DEL CAUCA),andrea.lond@hotmail.com,nan
4,5,,3124568025,CALLE 49 # 23-33,NEIVA (HUILA),dianabandrade63@gmail.com,nan

In [143]:
# Obtener la longitud del DataFrame df_detalles_contacto
num_filas = len(df_detalles_salario)

# Generar una secuencia de números para empleado_id
# Comenzando desde 1 hasta el número de filas en el DataFrame
empleado_ids = range(1, num_filas + 1)

# Insertar la columna 'empleado_id' al principio del DataFrame
df_detalles_salario.insert(0, 'empleado_id', empleado_ids)

# Guardar el DataFrame en un archivo CSV
df_detalles_salario.to_csv("static/salary_details.csv", index=False)
# df_detalles_contacto.to_csv("static/contact_details.csv", index=False)
df_detalles_salario.head()

,empleado_id,salario_o_ibc,mensajeria,vlr_mensajeria,vlr_administracion,vlr_upc,estado,valor_pila,valor_total
0,1,1160000,N,0,47000,0,Activo,58700,105700
1,2,1160000,N,0,47000,0,Activo,105100,152100
2,3,1160000,N,0,47000,0,Activo,98900,145900
3,4,1160000,N,0,47000,0,Activo,39500,86500
4,5,1160000,N,0,47000,0,Activo,96900,143900

In [167]:
# Obtener la longitud del DataFrame df_detalles_contacto
# num_filas = len(df_detalles_afiliacion)

# # Generar una secuencia de números para empleado_id
# # Comenzando desde 1 hasta el número de filas en el DataFrame
# empleado_ids = range(1, num_filas + 1)

# # Insertar la columna 'empleado_id' al principio del DataFrame
# df_detalles_afiliacion.insert(0, 'empleado_id', empleado_ids)
# desired_columns_order = [
#     "empleado_id", "fecha_afiliacion", "identificacion_asesor", "nombre_asesor", "afp",
#     "valor_comision", "afp_tarifa", "eps", "eps_tarifa", "arl", "arl_tarifa",
#     "arl_nivel", "cod_ciiu", "planilla_n", "ccf", "ciudad_ccf", "ccf_tarifa"]

# Reorder the columns in the DataFrame
# df_detalles_afiliacion = df_detalles_afiliacion.reindex(columns=desired_columns_order)
# Guardar el DataFrame en un archivo CSV
# df_detalles_afiliacion["ccf_tarifa", ""].fillna(0, inplace=True)

df_detalles_afiliacion.to_csv("static/affiliation_details.csv", index=False)
# df_detalles_contacto.to_csv("static/contact_details.csv", index=False)
df_detalles_afiliacion.head()

,empleado_id,fecha_afiliacion,identificacion_asesor,nombre_asesor,afp,valor_comision,afptarifa,eps,epstarifa,arl,arltarifa,arl_nivel,codciiu,planilla_n,ccf,ciudad_ccf,ccftarifa
0,1,2023-05-01,NaN,NaN,COLPENSIONES,0,0.16,EPS SANITAS,0.04,ARL SURA,0.00522,1,1461001,NO,COMCAJA - CAJA DE COMPENSACION FAMILIAR CAMPESINA,PUERTO CARREÃO (VICHADA),0.00
1,2,2023-07-01,NaN,NaN,PROTECCION,0,0.16,EPS SURA,0.04,ARL SURA,0.00522,1,1461001,NO,COMFANDI - CAJA DE COMPENSACION FAMILIAR DEL V...,CALI (VALLE DEL CAUCA),0.04
2,3,2023-07-01,NaN,NaN,NaN,0,NaN,NUEVA EPS,0.04,ARL SURA,0.00522,1,1461001,NO,COMFANDI - CAJA DE COMPENSACION FAMILIAR DEL V...,CALI (VALLE DEL CAUCA),0.04
3,4,2023-10-12,NaN,NaN,PORVENIR,0,0.16,EPS SANITAS,0.04,ARL SURA,0.00522,1,1461001,NO,COMCAJA - CAJA DE COMPENSACION FAMILIAR CAMPESINA,PUERTO CARREÃO (VICHADA),0.00
4,5,2023-07-01,NaN,NaN,NaN,0,NaN,NUEVA EPS,0.04,ARL SURA,0.04350,4,4461001,NO,COMCAJA - CAJA DE COMPENSACION FAMILIAR CAMPESINA,PUERTO CARREÃO (VICHADA),0.00

In [160]:
df_detalles_afiliacion.columns

Index(['empleado_id', 'fecha_afiliacion', 'identificacion_asesor',
       'nombre_asesor', 'valor_comision', 'afp', 'afptarifa', 'eps',
       'epstarifa', 'arl', 'arltarifa', 'arl_nivel', 'codciiu', 'planilla_n',
       'ccf', 'ciudad_ccf', 'ccftarifa'],
      dtype='object')

NameError: name 'Index' is not defined

In [165]:
column_order = ['empleado_id', 'fecha_afiliacion', 'identificacion_asesor',
                'nombre_asesor', 'afp', 'valor_comision', 'afptarifa', 'eps',
                'epstarifa', 'arl', 'arltarifa', 'arl_nivel', 'codciiu', 
                'planilla_n', 'ccf', 'ciudad_ccf', 'ccftarifa']

# Reordena el DataFrame según el orden deseado
df_detalles_afiliacion = df_detalles_afiliacion[column_order]

In [166]:
df_detalles_afiliacion

,empleado_id,fecha_afiliacion,identificacion_asesor,nombre_asesor,afp,valor_comision,afptarifa,eps,epstarifa,arl,arltarifa,arl_nivel,codciiu,planilla_n,ccf,ciudad_ccf,ccftarifa
0,1,2023-05-01,NaN,NaN,COLPENSIONES,0,0.16,EPS SANITAS,0.04,ARL SURA,0.00522,1,1461001,NO,COMCAJA - CAJA DE COMPENSACION FAMILIAR CAMPESINA,PUERTO CARREÃO (VICHADA),0.00
1,2,2023-07-01,NaN,NaN,PROTECCION,0,0.16,EPS SURA,0.04,ARL SURA,0.00522,1,1461001,NO,COMFANDI - CAJA DE COMPENSACION FAMILIAR DEL V...,CALI (VALLE DEL CAUCA),0.04
2,3,2023-07-01,NaN,NaN,NaN,0,NaN,NUEVA EPS,0.04,ARL SURA,0.00522,1,1461001,NO,COMFANDI - CAJA DE COMPENSACION FAMILIAR DEL V...,CALI (VALLE DEL CAUCA),0.04
3,4,2023-10-12,NaN,NaN,PORVENIR,0,0.16,EPS SANITAS,0.04,ARL SURA,0.00522,1,1461001,NO,COMCAJA - CAJA DE COMPENSACION FAMILIAR CAMPESINA,PUERTO CARREÃO (VICHADA),0.00
4,5,2023-07-01,NaN,NaN,NaN,0,NaN,NUEVA EPS,0.04,ARL SURA,0.04350,4,4461001,NO,COMCAJA - CAJA DE COMPENSACION FAMILIAR CAMPESINA,PUERTO CARREÃO (VICHADA),0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
68,69,2023-07-01,NaN,NaN,COLPENSIONES,0,0.16,NUEVA EPS,0.04,ARL SURA,0.00522,1,1461001,NO,COMFANDI - CAJA DE COMPENSACION FAMILIAR DEL V...,CALI (VALLE DEL CAUCA),0.04
69,70,2023-07-01,NaN,NaN,NaN,0,NaN,SALUD TOTAL EPS,0.04,ARL SURA,0.00522,1,1461001,NO,COMCAJA - CAJA DE COMPENSACION FAMILIAR CAMPESINA,PUERTO CARREÃO (VICHADA),0.00
70,71,2023-07-01,NaN,NaN,COLPENSIONES,0,0.16,EPS SANITAS,0.04,ARL SURA,0.00522,1,1461001,NO,COMFANDI - CAJA DE COMPENSACION FAMILIAR DEL V...,CALI (VALLE DEL CAUCA),0.04
71,72,2023-08-09,NaN,NaN,COLFONDOS,0,0.16,EPS SURA,0.04,ARL SURA,0.00522,1,1461001,NO,COMFANDI - CAJA DE COMPENSACION FAMILIAR DEL V...,CALI (VALLE DEL CAUCA),0.04
72,73,2023-07-01,NaN,NaN,PROTECCION,0,0.16,SALUD TOTAL EPS,0.04,ARL SURA,0.00000,0,1461001,NO,COMCAJA - CAJA DE COMPENSACION FAMILIAR CAMPESINA,PUERTO CARREÃO (VICHADA),0.00